name: Build and publish alpine-cmake-doxygen image

on:
  push:
      branches:
      - master
      paths:
      - 'alpine-cmake-doxygen/**'
  # workflow_call:
  #   outputs:
  #     description: 'image push output'
  #     value: ${{ jobs.push_to_registry.outputs.output }}
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
      NAME: alpine-cmake-doxygen
    outputs:
      output: ${{ steps.build.outputs.build }}
    steps:
      - name: check path
        run: pwd
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run:  echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=UTC-3 date +'%F-%H-%M')"
      - name: Build image
        id: build
        # run: echo "::set-output name=build::  DOCKER_BUILDKIT=1 docker build -t $LOGIN/$NAME:${{ steps.date.outputs.date }} -f alpine-cmake-doxygen/Dockerfile . }}"
        run: DOCKER_BUILDKIT=1 docker build -t $LOGIN/$NAME:${{ steps.date.outputs.date }} -f alpine-cmake-doxygen/Dockerfile . > /home/runner/work/private_dockers/private_dockers/builld_log_file.itxt
      - name: get build log
        id: log
        run: LOG=$(tail -n 20 /home/runner/work/private_dockers/private_dockers/builld_log_file.txt) echo "::set-output name=log::$LOG"
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${{ steps.date.outputs.date }}
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}

            ${{ steps.log.outputs.log }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}